
pdf:
	lualatex cv-studiorum.tex

open:
	evince cv-studiorum.pdf &
	

pdf1:
	pdflatex sig-clean.tex

pdf-bib:
	pdflatex sig-clean.tex
	bibtex sig-clean
	pdflatex sig-clean.tex
	pdflatex sig-clean.tex


